---
  name: Basic Docker Build
  
  on:
    push:
      branches:
        - main
    pull_request:
  
  jobs:
    build-image:
      name: Build Image
      runs-on: ubuntu-latest
      steps:
  
        - name: Checkout code
          uses: actions/checkout@v4
  
        - name: Set date and build number
          id: vars
          run: |
            DATE=$(date +%y.%-m.%-d)
            BUILD_NUM=${{ github.run_number }}
  
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
  
        - name: Docker Build
          uses: docker/build-push-action@v6
          with:
            push: ${{ github.event_name != 'pull_request' }}
            tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/myhttpenv:latest
              ${{ secrets.DOCKERHUB_USERNAME }}/myhttpenv:${{ steps.vars.outputs.full_tag }}